# Generated by Django 3.1.3 on 2020-11-15 11:44

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.BigIntegerField(default=time.time)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
